# Generated by Django 2.2.6 on 2020-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='white_list',
        ),
        migrations.AddField(
            model_name='room',
            name='max_length',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_number_of_user',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
