# Generated by Django 2.2.6 on 2020-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200415_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_length',
            field=models.IntegerField(default=-1, verbose_name='Maximum meeting time length (in Minutes)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_number_of_user',
            field=models.IntegerField(default=-1, verbose_name='Maximum number of users'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=255),
        ),
    ]
