# Generated by Django 2.2.6 on 2020-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20200417_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_join_time',
            field=models.BigIntegerField(null=True),
        ),
    ]
