# Generated by Django 2.2.6 on 2020-05-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200422_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_google_synced',
            field=models.BooleanField(default=False),
        ),
    ]
