# Generated by Django 2.2.6 on 2020-04-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
