# Generated by Django 2.2.6 on 2020-04-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_room_count', models.IntegerField(default=0, verbose_name='Maximum room a user can create')),
                ('max_time_length', models.IntegerField(default=0, verbose_name='Maximum time length of a room(in minute)')),
                ('max_member_count', models.IntegerField(default=0, verbose_name='Maximum number of guest in a room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
