# Generated by Django 2.2.6 on 2020-04-22 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restrictions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
